/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f030x8.h"




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Symbol definitions
#define LED_TIME_BLINK 500  //ms
#define LED_TIME_SHORT 1000 //ms
#define BTN_SAMPL_TIME 5    //ms

// Function declarations
void blikac(void);
void tlacitka(void);


// Global variables
volatile uint32_t Tick = 0;



//------------------ MAIN ------------------
int main(void) {

	SysTick_Config(8000); //1ms

	RCC->AHBENR  |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup

	RCC->APB2ENR      |= RCC_APB2ENR_SYSCFGEN; // enable clock
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PC; // select PC0 for EXTI0
	EXTI->IMR         |= EXTI_IMR_MR0; // mask
	EXTI->FTSR        |= EXTI_FTSR_TR0; // trigger on falling edge
	//NVIC_EnableIRQ(EXTI0_1_IRQn); // enable EXTI0_1


	/* Loop forever */
	for (;;) {
		blikac();
		tlacitka();
	}
}




// Disabled
void EXTI0_1_IRQHandler(void) {
	if (EXTI->PR & EXTI_PR_PR0) { // check line 0 has triggered the IT
		EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
		GPIOB->ODR ^= (1<<0);
	}
}

// 1ms Tick increment
void SysTick_Handler(void){
	Tick++;
}

// LED blinking
void blikac(void){
	static uint32_t delay = 0;

	if (Tick > delay + LED_TIME_BLINK) {
		GPIOA->ODR ^= (1<<4); // Toggle LED1 - pin PA4
		delay = Tick;
	}
}

// Button press and LED2 timer
void tlacitka(void){
	static uint16_t debounce  = 0xFFFF;
	static uint32_t off_time  = 0;
	static uint32_t delay     = 0;


	if (Tick > delay + BTN_SAMPL_TIME) {
		delay = Tick;

		debounce <<=1; // Bit shift left
		if (GPIOC->IDR & (1<<0)) debounce |= 0x0001; // and load button S1 (PC1) value to the LSB
		if (debounce == 0x8000) {
			off_time = Tick + LED_TIME_SHORT;
			GPIOB->BSRR = (1<<0);
		}
	}


	if (Tick > off_time) { // time to turn off the LED2
		GPIOB->BRR = (1<<0);
	}

}





